# Generated by Django 4.1.1 on 2022-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
