# Generated by Django 4.1.1 on 2022-09-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_post_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='book_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
