# Generated by Django 4.1.1 on 2022-09-19 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_postimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='customer/images'),
            preserve_default=False,
        ),
    ]
